### ISSUE TITLE
[REQUEST] Official 'Okay Assist' and 'Hey Assist' included as wake words by default for ESPHome and Home Assistant?

### ISSUE THREAD

**Issue by Hedda** [esphome/micro-wake-word-models#11]
Related to the request posted here:

- https://github.com/esphome/micro-wake-word-models/issues/8

Please also consider including a default wake word here that includes the word 'Assist' in a combination phrase as default or optional standard wakeword pharase, or rather and "**_Okay Assist_**" and "**_Hey Assist_**" phrases.

Are there any good reasons now why not included as standard wakeword phrases by default?

- _**Okay Assist.**_

and 

- _**Hey Assist.**_

As in

- "_**Okay Assist, turn on the dining room lights**_", and - "_**Hey Assist, turn off the kitchen lights**_", 

Here with "Assist" I am referring to Home Assistant's Assist for default conversation agent standard Assist pipeline in Home Assistant:

* https://www.home-assistant.io/voice_control/

The integration is also called Assist Satellite 

* https://www.home-assistant.io/integrations/assist_satellite/

and so is the Assist satellite entity

* https://developers.home-assistant.io/blog/2024/10/01/assist-satellite-entity/
  * https://developers.home-assistant.io/docs/core/entity/assist-satellite/
    * https://github.com/home-assistant/architecture/discussions/1136
      * https://github.com/home-assistant/core/pulls?q=is%3A+assist_satellite%22

After all, Home Assistant's official voice assistant is called "Assist", and there are even official logos and branding for that name.

![image](https://github.com/user-attachments/assets/4d4b4b64-8382-4142-97c9-850cd2274b3f)

My reasons for the request is partially for the same as in https://github.com/esphome/micro-wake-word-models/issues/8 which are that 'Nabu' / 'Nabucasa' does not have same brand recognition. Nabu as in Nabu Casa is also only the official partner to Open Home Foundation and the ESPHome and Home Assistant projects, so it does not make much sense of it being a default. 

Would be great with option to set simply 'Home Assistant' as default wake word as a way to show off and market for brand recognition.

Even on Nabu Casa's website it says that "Assist" is the official name that the voice assistant, so makes no sence "Nabu" being default?

* https://www.nabucasa.com/config/assist/

**Comment by Hedda** [comment]
FYI, as this request specifically applies to Home Assistant voice assistant I tried to submit this as a feature request section on the Home Assistant community forum but that thread was closed with comment from moderator that they do not accept ESPHome feature request there even if this is very much directly related to Home Assistant.

- https://community.home-assistant.io/t/have-assist-be-included-as-a-default-wake-word-in-the-official-esphome-micro-wake-word-model-collection/783483

**Comment by synesthesiam** [comment]
"Brand recognition" is not the only consideration for a wake word. It also needs to be unique enough that similar sounds won't be spoken frequently. This is why "computer" would be a poor choice, as it's a commonly used word. "Assist" is also a somewhat common word, so we went with "Nabu" which is also more fun to say 🙂

**Comment by Hedda** [comment]
What about the combinations ”_**Okay Assist**_” and/or ”_**Hey Assist**_” as combination phrases, as then it is not just the word ”Assist” on its own? 

Same question goes for ”_**Okay Home Assistant**_” and ”_**Hey Home Assistant**_” combination phrases as wakewords -> https://github.com/esphome/micro-wake-word-models/issues/8

Please at least consider including those as options even if not the default.

PS: Oh, by the way, as a non-English native speaking family none of those are are more commenly used words to say then than say ”Google” which today has become a synonym for searching for webpages on the internet 😉

**Comment by kahrendt** [comment]
I have no plans to train this particular wake words (or any other particular wake words) at this point. I will try to build a training script put together for people to experiment with creating their own wake words, so you can use whatever phrases you want.

If people contribute a model that performs well, I will be happy to add it to the repo.

**Comment by Hedda** [comment]
Why close as completed? Close as ”not planned” if officially rejected by the ESPHome as a whole or just leave it open if not officially rejected by the ESPHome as a whole and there is a chance someone else on the project will step up.

@kahrendt I understand you closing the one in your personal repo if you have no plans to do it yourself. But why close this one in this ESPHome project sub-repo? Maybe someone else see this request and are willing to create such a model for ESPHome.

**Comment by balloob** [comment]
This repository is not meant for feature requests. It’s only used to store the models that can be referenced by ESPHome by name. There is also no plan to currently make wake words that consist solely of generic words, as those will not perform well.
