### ISSUE TITLE
Possible copyright infringement if include ”Alexa” as a wake word in a commercial product?

### ISSUE THREAD

**Issue by Hedda** [esphome/micro-wake-word-models#12]
Slightly off-tanget, but wondering if you think it could possibly count as copyright infringement if one included ”Alexa” or ”Siri” and other already commercially used wakewords in your own commercial product?

No problems if individuals build DIY devices for personal use I am sure as then it is provably fair use, but to play it safe it would probably be a good idea to not include aleeady commercially used wake words like ”Alexa”, ”Siri”, ”Cortana”, and ”Bixby”, etc. In your own products that you plan to sell.

I am thinking of example Home Assistent’s upcoming voice-kit hardware as well as other thind-party hardware products that will use this framework as a platform.

**Comment by kahrendt** [comment]
The Alexa model is the worst performing of the four available, so that alone makes it not suitable for our satellite hardware. I have no idea what the legal implications are.
