### ISSUE TITLE
[id] is an invalid option for [models]. 

### ISSUE THREAD

**Issue by DunklerPhoenix** [esphome/micro-wake-word-models#15]
Heho
It seems that the "id" option for "models" is not correct. Does this need a specific version of esphome?

https://github.com/esphome/micro-wake-word-models/tree/main/models/v2/experiments

Greetings
Phoenix

**Comment by kahrendt** [comment]
Thanks for pointing this out! Removing the ``id`` option should make it work with the current mWW component in ESPHome.
