### ISSUE TITLE
hey_jarvis.tflite model keeps outputting 0 

### ISSUE THREAD

**Issue by yf-fan-org** [esphome/micro-wake-word-models#17]
hey_jarvis.tflite model always outputs 0, I would like to ask this model why I input random numbers but the output is always 0, is this model able to work properly?

[v2](https://github.com/esphome/micro-wake-word-models/tree/main/models/v2)

**Comment by kahrendt** [comment]
Let's continue any discussion in kahrendt/microWakeWord/issues/43
