### ISSUE TITLE
Custom Wake Words

### ISSUE THREAD

**Issue by rwrozelle** [esphome/micro-wake-word-models#6]
Hi,

Questions more than an issue or request.  Will the tflite files from https://github.com/fwartner/home-assistant-wakewords-collection work with micro-wake-words?  Be nice to just be able to add a json file and be on my way.  Also, can I store the tflite and json file local to ESPHOME folder?  Documentation doesn't seem to say that, but you never know until you ask.

**Comment by jerome83136** [comment]
Hi,
I think I have a similar question

I built a custom wakeword by using Google colab

And I got the following error when trying to compile the firmware:   "Not a valid model name, local path, http(s) url, or github shorthand."

I tried the following approaches:

- Hosting the model JSON + tfilte flite locally: (local DNS name + self-signed certificate for SSL)
```
micro_wake_word:
  model: https://domotique.maison.lan/statics/home-assistant/wakewords/eh_chou_pee.json
  on_wake_word_detected:
    then:
      - voice_assistant.start:
          wake_word: !lambda return wake_word;
```

- Hosting the model JSON + tfilte flite on my github account:
```
micro_wake_word:
  model: https://github.com/jerome83136/homeassistant/blob/main/eh_chou_pee.json
  on_wake_word_detected:
    then:
      - voice_assistant.start:
          wake_word: !lambda return wake_word;
```
 
All gave me the error "Not a valid model name, local path, http(s) url, or github shorthand."

But [ESPhome's documentation of microwakeword](https://esphome.io/components/micro_wake_word.html) clearly states that we can use an URL pointing to a JSON, referencing the tflite file for custom wakeword:

"A full URL to a model JSON file. e.g. https://github.com/esphome/micro-wake-word-models/raw/main/models/okay_nabu.json"

So: how can we use our custom wakewords with microwakeword please ?

Thank you for your help

Best regards

**Comment by jerome83136** [comment]
Hi everyone
Anyone able to help here maybe? 🙏
Thank you
Best regards

**Comment by devalgo1** [comment]
I have the same problem: the link to the file posted on github works. The link must be attached to the raw json file, then the compilation is successful. But the created model gives an error when running ESP32: "Component micro_wake_word is marked FAILED"

**Comment by marcelolcosta** [comment]
I also encountered the same issue.

**Comment by krisproger** [comment]
i also has the same 
but i got the next error
![image](https://github.com/user-attachments/assets/2a841460-76a2-4dd2-a1a7-88787a315a67)

link to json: https://mwhome.teplitzky.ru/local/share/openwakeword/ok_oomneeck.json
link to tflite: https://mwhome.teplitzky.ru/local/share/openwakeword/ok_oomneeck.tflite

**Comment by gustvao** [comment]
you guys need to update de ESP device before using the new yaml pattern

**Comment by ubergeekseven** [comment]
The bigger question here is how in the world did you actually get the micro wake word to train? The repo for microwakeword is not clear and there are a few issues within it specifically from the author stating he has not finished the training notebook and even the back and forth between one person and him goes over some missing portions.

Any update on this as well would be great. If anyone was able to jsut use their trained model from wakeword, that is nice too. Did you figure out how to get the model to load on the esp device?

**Comment by maciekish** [comment]
I have the same issue (i think)

```
micro_wake_word:
  on_wake_word_detected:
    - voice_assistant.start:
        wake_word: !lambda return wake_word;
  vad:
  models:
    - model: https://public.swic.name/computer.json
```

![image](https://github.com/user-attachments/assets/f615f0e7-bbf8-4774-af0b-0ad0cd8c9c1f)

**Comment by Revyen** [comment]
I get the "Not a valid model name, local path, http(s) url, or github shorthand." too. Tried via the git repo link

**Comment by balloob** [comment]
> Questions more than an issue or request. Will the tflite files from https://github.com/fwartner/home-assistant-wakewords-collection work with micro-wake-words?

Nope. You link to a repository that contains wake words for the openWakeWord engine. This repository contains files for microWakeWord engine (which runs inside ESPHome). They are not compatible.

**Comment by Git2tony** [comment]
Has anyone ever solved this? Or did I miss something? I'm currently trying to have a custom micro wake-word on a ESP32 S3 Wroom board, but got errors....

**Comment by ubergeekseven** [comment]
> Has anyone ever solved this? Or did I miss something? I'm currently trying to have a custom micro wake-word on a ESP32 S3 Wroom board, but got errors....

I would like to solve it for sure. I have not tried with the newest additions. have not had time.

**Comment by Equinox86** [comment]
> The bigger question here is how in the world did you actually get the micro wake word to train? The repo for microwakeword is not clear and there are a few issues within it specifically from the author stating he has not finished the training notebook and even the back and forth between one person and him goes over some missing portions.
> 
> Any update on this as well would be great. If anyone was able to jsut use their trained model from wakeword, that is nice too. Did you figure out how to get the model to load on the esp device?

As of 01-27-2025, after much trial and error, I was able to get the following setup to create a tflite for the wakeword: 
- Used the supplied notebook with vscode notebook addon. 
- Set up a virtual environment with python 3.10.14 using pyenv. 
    - Note: I tried 3.10.12 and ran into CuDnn issues. 
- When you open the notebook on the top right you can set the kernel to 3.10.14 and you should see your virtualenv as an option.
- Using the basic_training_notebook.ipynb run step 1. The microwakeword install failed for me. 
    - I think it needs to be the top level for the install (IE pip install -e ../microWakeWord)
    - It seems that the kernel needs to restart anyway so I just close vscode and install it from command line with the environment activated. 
- Downgrade tensorflow to 2.16.1.
- Reopen vscode and run the rest of the notebook.

That said, I am still having trouble getting the custom wakeword to work in esphome.

**Comment by Equinox86** [comment]
OK. So as it stands it seems like there is something only allowing the  default wakewords. 

For reference here's my custom microwakewords.

https://github.com/Equinox86/micro-wake-word-models/blob/main/models/hey_talos.json
https://github.com/Equinox86/micro-wake-word-models/blob/main/models/hey_talos.tflite

As a test I forked the micro-wake-words models, added my **microwakeword** model, and copied the json for "hey_jarvis" to "hey_talos", keeping the changes minimal.

![Image](https://github.com/user-attachments/assets/6f9c0908-e4f5-40ee-bdf0-9e9b2b873153)

It seems like no matter what I am getting this error. 

![Image](https://github.com/user-attachments/assets/3cf13fdd-d699-4524-8c1c-286865ef1103)

When I change "talos" to "jarvis" in the url, it compiles just fine.

Kinda seems like a configuration setting to check for only the supported wakewords, though I might be missing something.

**Comment by Equinox86** [comment]
Okay. So i am dumb. 

I had to clean the build files to complete the install. 

![Image](https://github.com/user-attachments/assets/a58617c5-39bc-49e5-9887-fb565e83cdab)

If you are running into this issue - hopefully that helps. 

Wakeword doesnt activate at all, but hey at least I can begin the phase of finding the right parameters.

**Comment by AlexGustafsson** [comment]
So the error message some of you've been seeing (`Not a valid model name, local path, http(s) url, or github shorthand.`) isn't necessarily telling the whole story. The error is shown not only if the URL is incorrect, but if the file's contents are incorrect. So make sure to check that the file is reachable on the specified URL and that everything looks okay. One thing to be vary of if you're trying to iterate on some file hosted by GitHub - they can cache it for a few minutes. So be sure to double check the contents of the URL you specify.

Here's an example of a working config:

```yaml
micro_wake_word:
  id: mww
  models:
    - model: https://raw.githubusercontent.com/alexgustafsson/esphome/refs/heads/main/models/microwakeword/cicero.json
      id: cicero
```

Here's another:

```yaml
micro_wake_word:
  id: mww
  models:
    - model: https://raw.githubusercontent.com/aegjoyce/microwakeword-custom-words/refs/heads/main/models/alfred.json
```

There's a nice guide here on how to train a model: https://github.com/kahrendt/microWakeWord/issues/65.

**Comment by raivisdejus** [comment]
My custom model was not working with this error, and to make it work I needed to set the `"version": 2,` in the json file of the custom model, then the issue went away.
