### ISSUE TITLE
Official 'Home Assistant' wake word

### ISSUE THREAD

**Issue by johnboiles** [esphome/micro-wake-word-models#8]
I think it would be great to have a default wake word here that's simply 'Home Assistant'. In my opinion, it would be the most obvious wake word for talking to Home Assistant.

'Nabu' / 'Nabucasa' doesn't have nearly the same brand reach/recognition as 'Home Assistant' and it would be great to nonchalantly show off my Home Assistant installation by talking to it.

I tried to train my own model on Google Colab, and it kinda worked, but wasn't as reliable as 'Ok Nabu'. If we made an officially supported one I bet together we could dial it in.

**Comment by DarthSonic** [comment]
I would be happy to see more wake words. There is a much larger selection for openwakewords.

**Comment by Hedda** [comment]
+1 for ”_**Okay Home Assistant”**_  and”_**Hey Home Assistant**_” as optional default wakeword combinations.

Might be to short to only have ”_**Home Assistant**_” as the wakeword, or?

- ”_**Home Assistant**_” 

So those longer wakewords should be unique and uncommon enough to work, or what do you think?

- ”_**Okay Home Assistant”**_ 

and the alternative

- ”_**Hey Home Assistant**_” 

PS: While waiting for input/feedback I suggest you also submit a request for unofficial community wakeword here -> https://github.com/fwartner/home-assistant-wakewords-collection/discussions/46

**Comment by johnboiles** [comment]
Submitted there thanks!

"Home Assistant" is 4 syllables where "Hey Jarvis"/"Hey Siri"/"Alexa" are all only 3. I bet simply "Home Assistant" would be plenty of audio to recognize. But I think "Hey Home Assistant"/"Okay Home Assistant" would be fine too!

**Comment by donburch888** [comment]
> 'Nabu' / 'Nabucasa' doesn't have nearly the same brand reach/recognition 

Brand recognition is actually negative, as it increases the chance that the brand name will be used in regular speech, falsely triggering the wake word.  "Computer" is popular (particularly with Star Trek fans) but is too likely to be used in other conversation. 
"Alexa" and "Siri" were not recognised brand names before they were used as wake words.

**Comment by Hedda** [comment]
While I admit being a super Home Assistant entusiast I promise that the sentence "**_Home Assistant_**" is said out loud at home  😜

I think it would be more than safe to have simply "**_Home Assistant_**" as the default wake word as standard for all 😄 

Niether does "Okay Assist" or "Hey Assist", ...maybe that is because we are non-native English speakers but I doubt that is why 🙄   

* https://github.com/esphome/micro-wake-word-models/issues/11

**Comment by kahrendt** [comment]
I have no plans to train this particular wake words (or any other particular wake words) at this point. I will try to build a training script put together for people to experiment with creating their own wake words, so you can use whatever phrases you want.

If people contribute a model that performs well, I will be happy to add it to the repo.

**Comment by Hedda** [comment]
Why close as completed? Close as ”not planned” if officially rejected by the ESPHome as a whole or just leave it open if not officially rejected by the ESPHome as a whole and there is a chance someone else on the project will step up.

@kahrendt I understand you closing the one in your personal repo if you have no plans to do it yourself. But why close this one in this ESPHome project sub-repo? Maybe someone else see this request and are willing to create such a model for ESPHome.

**Comment by balloob** [comment]
This repository is not meant for feature requests. It’s only used to store the models that can be referenced by ESPHome by name. There is also no plan to currently make wake words that consist solely of generic words, as those will not perform well.
